[ROLLOVER]
# The zone of which the keys are rolled e.g.
# zone = nl.
zone = 


[DATABASE]
# Absolute path to the SQLite DB file
db_path = 


[TTLS]
# The TTLs in seconds of the records that need to be replaced. Leave empty if not applicable
ttl_dnskey = 3600
ttl_rrsig = 3600
ttl_ds = 48000 


[MEASUREMENTS]
# Defines how often the probes will query for the records (in seconds)
msm_frequency_publication_delay = 120

# Measurements for propagation delay are carried out by default once every TTL.
# Change settings below if different frequency preferred
msm_frequency_propagation_delay_dnskey = 
msm_frequency_propagation_delay_rrsig = 
msm_frequency_propagation_delay_ds = 

# Domains to valid and bogus records to monitor the trust chain
trust_chain_valid =  
trust_chain_bogus = 


[NAMESERVERS]
# IP addresses of the authoritative name servers 
# These are necessary for monitoring the propagation delay
# Use ',' to separate IPs
# IPv4 and IPV6 addresses allowed
ips_child_ipv4 = 
ips_child_ipv6 = 
ips_parent_ipv4 = 
ips_parent_ipv6 = 


[RIPE]
# Your API key.
# With this key you must be able to create new measurements,
# read measurement results, and stop measurements
# Find more information here: https://atlas.ripe.net/docs/keys/
api_key = 

# Which probes should be used for the measurement
# Use 'all" for every available probe (user needs enough credits and raise their limits at RIPE)
# or use a number x to select x random probes
# or leave empty to configure probes more fine grained with settings below
probes = 10

# if setting 'probes' is empty you can select more fine grained here
# Probe IDs, separated by comma
probe_ids  

# AS number in which probes should be located, e.g. 1140
as_nr 

# Country in which the probes should be located
# Use ISO 3166 two letter country codes (e.g. NL, or US)
country   

# Continents on which the probes should be located
# Use comma separated two letter continent codes 
# (AF = Africa, AS=Asia, EU = EUROPE, NA = North America, SA = South America, OZ = Oceania)
continents 
